version: '3'

services:
  wyb-system:
    build: .
    ports:
      - "8765:8765"  # Kandidaten server
      - "8766:8766"  # Soy server
      - "8000:8000"  # HTTP server
    volumes:
      - ./videos:/app/videos
      - ./images:/app/images
      - ./presets:/app/presets
    environment:
      - KANDIDATEN_PORT=8765
      - SOY_PORT=8766
      - HTTP_PORT=8000
    restart: unless-stopped

